CREATE USER root WITH SUPERUSER CREATEDB CREATEROLE LOGIN;
CREATE USER ge_user WITH SUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD 'pG9tC4qI5lE3sB2e';
CREATE DATABASE expectations_store;
CREATE DATABASE de_demo;
GRANT ALL PRIVILEGES ON DATABASE expectations_store to ge_user;
GRANT ALL PRIVILEGES ON DATABASE de_demo to ge_user;
